# Generated by Django 5.1.3 on 2025-06-14 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_tags',
            field=models.ManyToManyField(blank=True, to='trips.tag'),
        ),
        migrations.AddField(
            model_name='tripparticipant',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['destination_city'], name='trips_trip_destina_4f50ec_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_date', 'end_date'], name='trips_trip_start_d_290e5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripparticipant',
            unique_together={('trip', 'user')},
        ),
    ]
